name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Parcel
        run: npm install -g parcel-bundler

      - name: Build Website
        run: parcel build src/*.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4